lane :test do
  poeditor_export(
    api_token: 'incert_your_api_token',
    project_id: 'incert_your_project_id',
    export_format: 'apple_strings',
    language: 'en',
    output_path: 'Localizable.strings'
  )
end
