lane :test do
  poeditor_export(
    api_token: "515cb74108a7a2a968aa9b759e2cf581",
    project_id: "56815",
    export_format: 'apple_strings',
    language: 'en',
    output_path: 'Localizable.strings'
  )
end
